# Generated by Django 3.2.3 on 2021-05-25 18:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Uuuid',
            fields=[
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('uuid_char', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
    ]
